### ISSUE TITLE
does not work with current ImageMagick 7.0.3-1

### ISSUE THREAD

**Issue by pke** [eberlitz/splashicon-generator#34]
```
$ magick --version
Version: ImageMagick 7.0.3-1 Q16 x64 2016-09-20 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib
```

And I am getting:
```
 Generating Icons for ios

{ Error: Command failed: Invalid Parameter - -set

    at ChildProcess.<anonymous> (C:\dev\projects\evopark\app\node_modules\imagemagick\imagemagick.js:88:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) timedOut: false, killed: false, code: 4, signal: null }
```

This has to do with resizing, since this is the only one that uses the "-set" argument for sharpening.

**Comment by eberlitz** [comment]
Check out this issue #23

**Comment by eberlitz** [comment]
I also updated the README describing this

**Comment by pke** [comment]
Thanks!
